### Footstep parameterization for the Aldebaran Robotics Nao humanoid #########

### footstep settings #########################################################
# Footstep displacement vectors (in meter / rad)
# WARNING: data type has to be float since integers will cause an exception
footsteps:
  x:     [0.00, 0.04,-0.03, 0.00, 0.04, 0.01, 0.015, 0.04,-0.03, 0.04, 0.04,-0.02]
  y:     [0.1, 0.1, 0.1,0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  theta: [0.00, 0.00, 0.00, 0.00, 0.00,-0.05, 0.05, 0.05, 0.05, 0.00, 0.00, 0.00]


### foot settings #############################################################
foot:
  size: {x: 0.185, y: 0.085, z: 0.015}
  separation: 0.1
  origin_shift: {x: 0.02, y: 0.006}
  max:
    step: {x: 0.04, y: 0.12, theta: 0.05}
    inverse:
      step: {x: -0.03, y: 0.09, theta: -0.05}


### step range ################################################################

# more accurate than the bounding box defined by the max/max inverse step
step_range:
  x: [0.00, 0.01, 0.02, 0.03, 0.04, 0.04, 0.04, 0.04,-0.03,-0.03,-0.02,-0.01]
  y: [0.12, 0.12, 0.12, 0.12, 0.12, 0.11, 0.10, 0.095, 0.090, 0.10, 0.11, 0.12]
